webcuoiky/webcuoiky/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webcuoiky.Controllers
{
    public class DefaultController : Controller
    {
        //
        // GET: /Default/

        public ActionResult Default()
        {
            return View();
        }

    }
}

webcuoiky/webcuoiky/Views/Shared/Default.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   
    <meta name="keywords" content="" />
    <meta name="Premium Series" content="" />
    <link href="default.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
    <link href="~/Content/Style.css" rel="stylesheet" />
    <link href="~/Content/Default.css" rel="stylesheet" />
    <div id="header">
        <div id="logo">
            <h1><a href="@Url.Action("trangmoi", "Default")">CatApp</a></h1>
            <div class="content-wrapper">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>
        <div id="menu">
            @Styles.Render("~/Content/css")
            @Scripts.Render("~/bundles/modernizr")
            <ul id="main">
                <li class="current_page_item"><a href="http://localhost:1360/">Home</a></li>
                <li><a href="http://localhost:1360/CatMart/Index">CatMart</a></li>
                <li><a href="http://localhost:1360/CatHealth/Index">CatHealth</a></li>
                <li><a href="http://localhost:1360/Blog/Index">Blog</a></li>
                <li><a href="http://localhost:1360/MommentCute/Index">MommentCute</a></li>
            </ul>
            <ul id="feed">
                <li><a href="#">Login</a></li>
                <li><a href="#">Register</a></li>
            </ul>
        </div>

    </div>
    <!-- end header -->
    <div id="wrapper">
        <!-- start page -->
        <div id="page">
            <div id="sidebar1" class="sidebar">
                <ul>
                    <li>
                        <h2>Recent Posts</h2>
                        <ul>
                           
                            <li><a href="http://localhost:1360/CafeMeo/Index">CafeMeo</a></li>
                            <li><a href="http://localhost:1360/TinTuc/Index">TinTuc</a></li>
                            
                        </ul>
                    </li>
                    <li>
                        
                    </li>
                    <li>
                        
                    </li>
                    <li>
                       
                    </li>
                </ul>
            </div>
            <!-- start content -->
            <div id="content">
                <div class="flower"><img src="http://localhost:1360/Images/h1.jpg" alt="" width="510" height="250" /></div>
                <div class="post">
                    <h1 class="title"><a href="#">Welcome to CATAPP!</a></h1>
                   
                   
                </div>
                <div class="post">
         
                    <div class="entry">
                        

                        <div>
                            @RenderBody()
                        </div>
                     
                       
                    </div>
                </div>
                <div class="post">
                   
                </div>
            </div>
            <!-- end content -->
            <!-- start sidebars -->
            <div id="sidebar2" class="sidebar">
                <ul>
                    <li>
                        <form id="searchform" method="get" action="#">
                         
                        </form>
                    </li>
                    
                    <li>
                        <h2>Calendar</h2>
                        <div id="calendar_wrap">
                            <table summary="Calendar">
                                <caption>
                                    October 2009
                                </caption>
                                <thead>
                                    <tr>
                                        <th abbr="Monday" scope="col" title="Monday">M</th>
                                        <th abbr="Tuesday" scope="col" title="Tuesday">T</th>
                                        <th abbr="Wednesday" scope="col" title="Wednesday">W</th>
                                        <th abbr="Thursday" scope="col" title="Thursday">T</th>
                                        <th abbr="Friday" scope="col" title="Friday">F</th>
                                        <th abbr="Saturday" scope="col" title="Saturday">S</th>
                                        <th abbr="Sunday" scope="col" title="Sunday">S</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <td abbr="September" colspan="3" id="prev"><a href="#" title="View posts for September 2009">&laquo; Sep</a></td>
                                        <td class="pad">&nbsp;</td>
                                        <td colspan="3" id="next">&nbsp;</td>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>2</td>
                                        <td>3</td>
                                        <td id="today">4</td>
                                        <td>5</td>
                                        <td>6</td>
                                        <td>7</td>
                                    </tr>
                                    <tr>
                                        <td>8</td>
                                        <td>9</td>
                                        <td>10</td>
                                        <td>11</td>
                                        <td>12</td>
                                        <td>13</td>
                                        <td>14</td>
                                    </tr>
                                    <tr>
                                        <td>15</td>
                                        <td>16</td>
                                        <td>17</td>
                                        <td>18</td>
                                        <td>19</td>
                                        <td>20</td>
                                        <td>21</td>
                                    </tr>
                                    <tr>
                                        <td>22</td>
                                        <td>23</td>
                                        <td>24</td>
                                        <td>25</td>
                                        <td>26</td>
                                        <td>27</td>
                                        <td>28</td>
                                    </tr>
                                    <tr>
                                        <td>29</td>
                                        <td>30</td>
                                        <td>31</td>
                                        <td class="pad" colspan="4">&nbsp;</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </li>
                    <li>
             
                    </li>
                </ul>
            </div>
            <!-- end sidebars -->
            <div style="clear: both;">&nbsp;</div>
        </div>
        <!-- end page -->
    </div>
 

    
    @RenderSection("scripts",required: false)
</body>
</html>

webcuoiky/webcuoiky/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>